server:
  port: 9080
keycloak:
  auth-server-url: http://localhost:8190
  realm: knowledgefactory-realm
  resource: knowledgefactory-client
  public-client: true
  bearer-only: true
#  use-resource-role-mappings: true
#  ssl-required: external
#  connection-timeout: 6000
spring:
  data:
    mongodb:
      database: fabrica
      port: 27017
      host: localhost
  